# Nome da Action
name: Snake Game

# Eventos que disparam o workflow
on:
  schedule:
    # Será atualizado a cada 5 horas
    - cron: "0 */5 * * *"
  # Permite executar manualmente pela interface do GitHub
  workflow_dispatch:

# Regras do job
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v2

      # Gera os arquivos SVG e GIF da cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: w1rys # Seu usuário GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # (Opcional) Verifica o status do Git
      - run: git status

      # Faz push das alterações para o branch master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica o conteúdo no GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
